from typing       import TYPE_CHECKING, Literal, overload
from numpy.typing import NDArray

if TYPE_CHECKING:
    from .core import Node, hkReferencedObjectNode


    class hkaAnimationContainerNode(hkReferencedObjectNode):

        @overload
        def __getitem__(self, key: Literal["skeletons"]) -> list[int]: ...  # hkaSkeleton
        @overload
        def __getitem__(self, key: Literal["animations"]) -> list[int]: ...  # hkaAnimation
        @overload
        def __getitem__(self, key: Literal["bindings"]) -> list[int]: ...  # hkaAnimationBinding
        @overload
        def __getitem__(self, key: Literal["attachments"]) -> list[int]: ...  # hkaBoneAttachment
        @overload
        def __getitem__(self, key: Literal["skins"]) -> list[int]: ...  # hkaMeshBinding

        @overload
        def __setitem__(self, key: Literal["skeletons"], value: list[int]) -> None: ...  # hkaSkeleton
        @overload
        def __setitem__(self, key: Literal["animations"], value: list[int]) -> None: ...  # hkaAnimation
        @overload
        def __setitem__(self, key: Literal["bindings"], value: list[int]) -> None: ...  # hkaAnimationBinding
        @overload
        def __setitem__(self, key: Literal["attachments"], value: list[int]) -> None: ...  # hkaBoneAttachment
        @overload
        def __setitem__(self, key: Literal["skins"], value: list[int]) -> None: ...  # hkaMeshBinding

    class hkaBoneNode(Node):

        @overload
        def __getitem__(self, key: Literal["name"]) -> str: ...
        @overload
        def __getitem__(self, key: Literal["lockTranslation"]) -> int: ...

        @overload
        def __setitem__(self, key: Literal["name"], value: str) -> None: ...
        @overload
        def __setitem__(self, key: Literal["lockTranslation"], value: int) -> None: ...

    class hkaSkeletonNode(hkReferencedObjectNode):

        @overload
        def __getitem__(self, key: Literal["name"]) -> str: ...
        @overload
        def __getitem__(self, key: Literal["parentIndices"]) -> list[int]: ...
        @overload
        def __getitem__(self, key: Literal["bones"]) -> list[int]: ...  # hkaBone
        @overload
        def __getitem__(self, key: Literal["referencePose"]) -> NDArray: ...
        @overload
        def __getitem__(self, key: Literal["referenceFloats"]) -> list[float]: ...
        @overload
        def __getitem__(self, key: Literal["floatSlots"]) -> list[str]: ...
        @overload
        def __getitem__(self, key: Literal["localFrames"]) -> list[int]: ...  # hkaSkeletonLocalFrameOnBone

        @overload
        def __setitem__(self, key: Literal["name"], value: str) -> None: ...
        @overload
        def __setitem__(self, key: Literal["parentIndices"], value: list[int]) -> None: ...
        @overload
        def __setitem__(self, key: Literal["bones"], value: list[int]) -> None: ...  # hkaBone
        @overload
        def __setitem__(self, key: Literal["referencePose"], value: NDArray) -> None: ...
        @overload
        def __setitem__(self, key: Literal["referenceFloats"], value: list[float]) -> None: ...
        @overload
        def __setitem__(self, key: Literal["floatSlots"], value: list[str]) -> None: ...
        @overload
        def __setitem__(self, key: Literal["localFrames"], value: list[int]) -> None: ...  # hkaSkeletonLocalFrameOnBone

    class hkaSkeletonMapperNode(hkReferencedObjectNode):

        @overload
        def __getitem__(self, key: Literal["mapping"]) -> int:...  # hkaSkeletonMapperData

        @overload
        def __setitem__(self, key: Literal["mapping"], value: int) -> None:...  # hkaSkeletonMapperData

    class hkaSkeletonMapperDataNode(Node):

        @overload
        def __getitem__(self, key: Literal["skeletonA"]) -> int:...  # hkaSkeleton
        @overload
        def __getitem__(self, key: Literal["skeletonB"]) -> int:...  # hkaSkeleton
        @overload
        def __getitem__(self, key: Literal["simpleMappings"]) -> list[int]:...  # hkaSkeletonMapperDataSimpleMapping
        @overload
        def __getitem__(self, key: Literal["chainMappings"]) -> list[int]:...  # hkaSkeletonMapperDataChainMapping
        @overload
        def __getitem__(self, key: Literal["unmappedBones"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["extractedMotionMapping"]) -> list[float]:...
        @overload
        def __getitem__(self, key: Literal["keepUnmappedLocal"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["mappingType"]) -> int:...

        @overload
        def __setitem__(self, key: Literal["skeletonA"], value: int) -> None:...  # hkaSkeleton
        @overload
        def __setitem__(self, key: Literal["skeletonB"], value: int) -> None:...  # hkaSkeleton
        @overload
        def __setitem__(self, key: Literal["simpleMappings"], value: list[int]) -> None:...  # hkaSkeletonMapperDataSimpleMapping
        @overload
        def __setitem__(self, key: Literal["chainMappings"], value: list[int]) -> None:...  # hkaSkeletonMapperDataChainMapping
        @overload
        def __setitem__(self, key: Literal["unmappedBones"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["extractedMotionMapping"], value: list[float]) -> None:...
        @overload
        def __setitem__(self, key: Literal["keepUnmappedLocal"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["mappingType"], value: int) -> None:...

    class hkaSkeletonMapperDataChainMappingNode(Node):

        @overload
        def __getitem__(self, key: Literal["startBoneA"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["endBoneA"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["startBoneB"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["endBoneB"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["startAFromBTransform"]) -> list[float]:...
        @overload
        def __getitem__(self, key: Literal["endAFromBTransform"]) -> list[float]:...

        @overload
        def __setitem__(self, key: Literal["startBoneA"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["endBoneA"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["startBoneB"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["endBoneB"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["startAFromBTransform"], value: list[float]) -> None:...
        @overload
        def __setitem__(self, key: Literal["endAFromBTransform"], value: list[float]) -> None:...

    class hkaSkeletonMapperDataSimpleMappingNode(Node):

        @overload
        def __getitem__(self, key: Literal["boneA"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["boneB"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["aFromBTransform"]) -> list[float]:...

        @overload
        def __setitem__(self, key: Literal["boneA"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["boneB"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["aFromBTransform"], value: list[float]) -> None:...


    class hkaAnimationBindingNode(hkReferencedObjectNode):

        @overload
        def __getitem__(self, key: Literal["originalSkeletonName"]) -> str:...
        @overload
        def __getitem__(self, key: Literal["animation"]) -> int:...  # hkaAnimation
        @overload
        def __getitem__(self, key: Literal["transformTrackToBoneIndices"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["floatTrackToFloatSlotIndices"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["partitionIndices"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["blendHint"]) -> int:...

        @overload
        def __setitem__(self, key: Literal["originalSkeletonName"], value: str) -> None:...
        @overload
        def __setitem__(self, key: Literal["animation"], value: int) -> None:...  # hkaAnimation
        @overload
        def __setitem__(self, key: Literal["transformTrackToBoneIndices"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["floatTrackToFloatSlotIndices"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["partitionIndices"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["blendHint"], value: int) -> None:...

    class hkaAnimationNode(hkReferencedObjectNode):

        @overload
        def __getitem__(self, key: Literal["type"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["duration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["numberOfTransformTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["numberOfFloatTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["extractedMotion"]) -> int:...  # hkaAnimatedReferenceFrame
        @overload
        def __getitem__(self, key: Literal["annotationTracks"]) -> list[int]:...  # hkaAnnotationTrack

        @overload
        def __setitem__(self, key: Literal["type"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["duration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfTransformTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfFloatTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["extractedMotion"], value: int) -> None:...  # hkaAnimatedReferenceFrame
        @overload
        def __setitem__(self, key: Literal["annotationTracks"], value: list[int]) -> None:...  # hkaAnnotationTrack

    class hkaQuantizedAnimationNode(hkaAnimationNode):

        @overload
        def __getitem__(self, key: Literal["type"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["duration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["numberOfTransformTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["numberOfFloatTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["extractedMotion"]) -> int:...  # hkaAnimatedReferenceFrame
        @overload
        def __getitem__(self, key: Literal["annotationTracks"]) -> list[int]:...  # hkaAnnotationTrack

        @overload
        def __setitem__(self, key: Literal["type"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["duration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfTransformTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfFloatTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["extractedMotion"], value: int) -> None:...  # hkaAnimatedReferenceFrame
        @overload
        def __setitem__(self, key: Literal["annotationTracks"], value: list[int]) -> None:...  # hkaAnnotationTrack


        @overload
        def __getitem__(self, key: Literal["data"]) -> bytes:...
        @overload
        def __getitem__(self, key: Literal["endian"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["skeleton"]) -> None:...

        @overload
        def __setitem__(self, key: Literal["data"], value: bytes) -> None:...
        @overload
        def __setitem__(self, key: Literal["endian"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["skeleton"], value: None) -> None:...

    class hkaInterleavedUncompressedAnimationNode(hkaAnimationNode):

        @overload
        def __getitem__(self, key: Literal["type"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["duration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["numberOfTransformTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["numberOfFloatTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["extractedMotion"]) -> int:...  # hkaAnimatedReferenceFrame
        @overload
        def __getitem__(self, key: Literal["annotationTracks"]) -> list[int]:...  # hkaAnnotationTrack
        
        @overload
        def __setitem__(self, key: Literal["type"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["duration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfTransformTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfFloatTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["extractedMotion"], value: int) -> None:...  # hkaAnimatedReferenceFrame
        @overload
        def __setitem__(self, key: Literal["annotationTracks"], value: list[int]) -> None:...  # hkaAnnotationTrack


        @overload
        def __getitem__(self, key: Literal["transforms"]) -> NDArray:...
        @overload
        def __getitem__(self, key: Literal["floats"]) -> NDArray:...

        @overload
        def __setitem__(self, key: Literal["transforms"], value: NDArray) -> None:...
        @overload
        def __setitem__(self, key: Literal["floats"], value: NDArray) -> None:...

    class hkaSplineCompressedAnimationNode(hkaAnimationNode):

        @overload
        def __getitem__(self, key: Literal["type"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["duration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["numberOfTransformTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["numberOfFloatTracks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["extractedMotion"]) -> int:...  # hkaAnimatedReferenceFrame
        @overload
        def __getitem__(self, key: Literal["annotationTracks"]) -> list[int]:...  # hkaAnnotationTrack
        
        @overload
        def __setitem__(self, key: Literal["type"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["duration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfTransformTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["numberOfFloatTracks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["extractedMotion"], value: int) -> None:...  # hkaAnimatedReferenceFrame
        @overload
        def __setitem__(self, key: Literal["annotationTracks"], value: list[int]) -> None:...  # hkaAnnotationTrack


        @overload
        def __getitem__(self, key: Literal["numFrames"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["numBlocks"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["maxFramesPerBlock"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["maskAndQuantizationSize"]) -> int:...
        @overload
        def __getitem__(self, key: Literal["blockDuration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["blockInverseDuration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["frameDuration"]) -> float:...
        @overload
        def __getitem__(self, key: Literal["blockOffsets"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["floatBlockOffsets"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["transformOffsets"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["floatOffsets"]) -> list[int]:...
        @overload
        def __getitem__(self, key: Literal["data"]) -> bytes:...
        @overload
        def __getitem__(self, key: Literal["endian"]) -> int:...

        @overload
        def __setitem__(self, key: Literal["numFrames"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["numBlocks"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["maxFramesPerBlock"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["maskAndQuantizationSize"], value: int) -> None:...
        @overload
        def __setitem__(self, key: Literal["blockDuration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["blockInverseDuration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["frameDuration"], value: float) -> None:...
        @overload
        def __setitem__(self, key: Literal["blockOffsets"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["floatBlockOffsets"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["transformOffsets"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["floatOffsets"], value: list[int]) -> None:...
        @overload
        def __setitem__(self, key: Literal["data"], value: bytes) -> None:...
        @overload
        def __setitem__(self, key: Literal["endian"], value: int) -> None:...
        